### ISSUE TITLE
FR: Allow customisation of all camera controls offered by picamera2

### ISSUE THREAD

**Issue by roamingthings** [roamingthings/spyglass#22]
Picamera2 provides a rich set of [camera controls](https://github.com/raspberrypi/picamera2/blob/af75efd3b76479a2f6401dda120a67f3ee417eea/apps/app_full.py#L1149) that allow to adjust the camera operation.

Spyglass should allow the user to configure these controls to optimize image, stream and video quality.

## Questions

* How should the controls be configured?
  * cli
  * configuration file (specified by cli argument)
  * HTTP/REST endpoint
* Should it be possible to update the controls during streaming or just at the start of spyglass?

**Comment by roamingthings** [comment]
After looking at all available configuration properties I'm not sure if it makes sense to allow the user to customize all available settings. I can understand that it may be tempting but there's a lot that can be done wrong. And at the end spyglass has a certain use-case in mind.

So I would argue to take a look at all available controls and only support controls that make sense to us and/or add more controls later when they are requested by actual users.

**Comment by mryel00** [comment]
I would still offer all the controls through something like I mentioned in #14, as it gives more advanced users a better control over their camera.
It would make sense to implement easy to use cli arguments for the most used once but artificially limit them until someone requests them doesn't make sense in my opinion.

**Comment by roamingthings** [comment]
I agree. It's just that not all controls make sense. I will post a list later. Then we can see which make sense and which don't.

**Comment by roamingthings** [comment]
I think that we should limit the options to a meaningful set. Adding options later is easier than taking them away.

Maybe let's start with a few controls first and see how it goes.

**Comment by mryel00** [comment]
@roamingthings I've added now a HTML page for all controls and what controls get parsed and processed. The list of all controls can be accessed with `http://<ip.of.your.pi>:<port>/options` and the settings can be live adjusted with `http://<ip.of.your.pi>:<port>/options?brightness=0.3&afmode=2`. Those adjusted settings don't get saved.
On the pictures you can see the overview and an example of the control parsing. Only controls really available get processed. The controls are case insensitive. Currently all controls are allowed, adding a list of limited controls isn't that hard, but I would need a list for that first. But I still don't like the limit, even if some parameters doesn't make sense to have. If there are newer cams with god knows what new controls, the list would need an update. So a list excluding controls instead of a list defining allowed controls maybe makes more sense? But even such a list would need maintenance in future.

I would appreciate some feedback and suggestions for the HTML page. The table is spread over the whole page.
![image](https://github.com/roamingthings/spyglass/assets/58853838/dae3d0cf-94bf-451c-8b7e-a78d78fa0a14)
![image](https://github.com/roamingthings/spyglass/assets/58853838/69c42344-9bb3-4409-869f-8ab89b1aafc7)

**Comment by roamingthings** [comment]
This is a great feature and I like the information that is displayed on the page.
I think that only a bit of CSS is required.

**Comment by mryel00** [comment]
Merged with #14
