### ISSUE TITLE
FR: Add option to rotate the image

### ISSUE THREAD

**Issue by roamingthings** [roamingthings/spyglass#33]
Sometimes camera modules will be mounted at a rotated angle. To compensate for that it would be helpful to have an option that rotates the image so it will be displayed correctly.

**Comment by mryel00** [comment]
180° degree rotation is already implemented with #13 
There isn't anything noted about 90° or 270° rotations in the picamera2 documentation so we need to process the frame before sending it.

**Comment by mryel00** [comment]
I added the exif based image/video rotation because it will generate no overhead on the Pi as it only sends about 100 bytes more per frame and those bytes don't have to be processed. The only processing done is calculating the byte value of a number between 1 and 8.
Other options would be processing the image with something like PIL or OpenCV. Both creating extra overhead on the Pi.
