### ISSUE TITLE
Impossible to install spyglass!!

### ISSUE THREAD

**Issue by djepsylon** [roamingthings/spyglass#51]
hi, 
few hours ago i try to install  spyglass for use a pi camerza module 3 with mainsail and crowsnest.
but when i launch command i have ab error and when i clone manually the repo impossible to launch install what s wrong?
![WM-Screenshots-20230528020020](https://github.com/roamingthings/spyglass/assets/96573654/4ee7bfc5-caac-42ad-8f6d-b6b4fcf9cd70)

can you tell me how install it on my pi 4 please?

i ve tried that:
cd ~

git clone https://github.com/roamingthings/spyglass

cd spyglass

./run.py

but no way i ve tried wit sudo too but same results. i ve tried to create folder manually with no results again

**Comment by mryel00** [comment]
Hey, here are mulitple different errors.

First of all you should only use spyglass and crowsnest together, if you want to use spyglass for a camera module v3 and crowsnest for an USB camera. Also in the newest version of crowsnest you can use crowsnest for a camera module v3. If you want support for the exif rotation feature (90° and 270° rotation possible, directly in your browser) then you have to use spyglass, otherwise you could use crowsnest too.

Second, the first error....I guess you got the problem yourself there.... The second issue you got isn't related to spyglass in any way. The last two errors refers to `git` not available on your system. If you google that error, you get like 34.000.000 hits. 
It could be either that your `git` command isn't on the path or you don't have git installed.

Third, ofc you can't `cd` (**c**hange **d**irectory) if your clone is failing as the directory won't be created and if you just create an empty directory, `make install` can't work too. `make` just executes the commands of a `Makefile`. This `Makefile` is something that is lying inside the repository folder that you clone. It's not a magic tool that can just install every GitHub repository just based on the name of the parent folder.

I would prefer if people could first use a search engine to find a solution for their error to see if it's an overall problem or really a problem with a repository like spyglass, as this would save us all some time.

Also please don't copy just random stuff and hope that it's working, as you did in the beginning of the terminal output. This could introduce errors in other repos if you use the wrong commands at the wrong time. You should always roughly understand what a command is doing before randomly using it and hoping that it's doing what you want. Our installation guide isn't the best for beginners atm tbh (mostly `git clone` is missing) but these problems you got will never be covered in there as these are just basic Linux usage problems.

I hope you read everything and understood how you can find the solution to your problem. I won't post the commands here as I can't be 100% sure what the error is and there are really enough posts online about this problem.
With this all said, I will close this issue and hope you will be able to fix it by yourself

**Comment by djepsylon** [comment]
hi,
thanks for your answer.
I'm sorry to have wasted your time, but I can assure you that we tried to do our own research before posting anything here.
If you wish I can provide you with the browsing history from that day, we spent hours trying to get spyglass to work without success, git is well installed because when I do a git --version I get the git version number displayed, on the screen I sent you I just resent the command to show you that it doesn't work but I did everything you said before. 
then, we have the latest version of crownest installed and despite having activated the drivers for the v3 camera (imx708 if my memory is correct) with dtoverlay=imx708 we manage to have the camera recognised by the raspberry but when we try to read the stream, by entering "the address of the pi":8080/stream one time out of two, we get the mainsail home page or nothing at all. this is why we tried using spyglass.

**Comment by mryel00** [comment]
Hey @djepsylon ,
I'm sry if I was a bit rude but the error shown in your sreenshot you send is clear. You don't have `git` installed or you are not writing `git` correct. You would get another error if there would be a problem with the repository that you want to clone or trying to use.
If you get another error than in your screenshot then please send it and I will reopen this issue and further assist you on that.

For crowsnest support you could go to the [Mainsail Discord](https://discord.gg/mainsail) into the support-forum and create a post there. There is also a post pinned that we used as a support thread for spyglass.

**Comment by djepsylon** [comment]
hi @mryel00  i ve solve my problem, i ve maked a basic procedure for noobs if you want for everytone who is interessed but in french but with google trad it could be easy. this what ive do and it work well

"sudo apt-update"
-"sudo apt-upgrade"
-Désinstaller crownest
-Verifier que la camera est detectée ==> "libcamera-hello --list-camera"
-Installer picamera2 :"sudo apt install -y python3-pyqt5 python3-opengl"
-cd ~
-Spyglass==> -"git clone https://github.com/roamingthings/spyglass.git"
                          -"cd spyglass"
                          -"./run.py"
-verifier si le stream fonctionne en ouvrant une page internet avec "<adresseipdupi>:8080/stream" et la video devrait s afficher.
faire que le script se lance au demarrage ==> -"sudo crontab -e" et ca ouvre un fichier et ajouter la ligne suivant a la fin.-"@reboot python3 /home/pi/spyglass/run.py -r 1920x1080 -f 10 -af manual -l 4.5"
-Pour la config de cam dans mainsail==> pour le flux et l instantané la meme adresse: "webcam/stream"
                                                                             -le service: UV4L-MJPEG (modifié)
30 mai 2023

**Comment by mryel00** [comment]
Hey @djepsylon ,
good to hear that you solved it but I have two things that should be changed in your basic procedure.
On a Raspberry Pi with bullseye there is already everything installed for `picamera2`. Also this command for installing `picamera2` is only installing some dependencies and those aren't needed for spyglass to work afaik. They should be only there if you want a preview window but spyglass doesn't provide that functionality.
Instead of `crontab` you should be able to use the service. If everything got cloned and you verified that it's working, you can execute `cd ~/spyglass && make install`. This will install a service that you can configure with the spyglass.conf file located inside `~/printer_data/config` after you installed the service. This executes spyglass on every restart as well and is a bit easier to edit.

I will add a more detailed tutorial on setting everything up asap on GitHub as I already wrote something up that I posted on the thread I mentioned earlier.
